### PR TITLE
Fix migration file.  No such column in users table.  Not sure how thi…

### PR DESCRIPTION
**Pull request by rmcgirr83**
…s was missed during validation

### CODE REVIEW

**Comment by rmcgirr83** [comment]
El bumpo @Elsensee

**Comment by Elsensee** [comment]
Oh, thanks.

Probably because install and uninstall worked. Not sure how this was missed when coding it.
Will merge it in the next 1-2 days, pretty short on time right now. (as in, I shouldn't even have time to write this)

**Comment by Elsensee** [comment]
Actually, let me just merge this straight away.

**Comment by rmcgirr83** [comment]
:+1:

**Pull request merged**
